// Shared mock data for the Clients module

export type Industry =
  | 'Healthcare' | 'IT' | 'Engineering' | 'Finance'
  | 'Manufacturing' | 'Government' | 'Professional Services' | 'Other'

export type Client = {
  id: string
  name: string
  displayName: string
  legalName: string
  industry: Industry
  companyType: 'direct' | 'vms'
  status: 'active' | 'prospect' | 'inactive'
  website: string
  taxId: string
  companySize: string
  city: string
  state: string
  country: string
  zip: string
  timezone: string
  accountOwner: string
  recruitmentManager: string
  primaryRecruiter: string
  clientSince: string
  lastActivity: string
  tags: string[]
  preferredCommunication: string
  preferredSubmissionMethod: string
  preferredResumeFormat: string
  preferredInterviewProcess: string
  specialInstructions: string
}

export type ClientContact = {
  id: string
  clientId: string
  name: string
  title: string
  department: string
  email: string
  phone: string
  mobile: string
  linkedin: string
  preferredContactMethod: string
  decisionMaker: boolean
  primary: boolean
  status: 'active' | 'inactive'
  notes: string
}

export type ClientFacility = {
  id: string
  clientId: string
  name: string
  type: 'Hospital' | 'Clinic' | 'Laboratory' | 'Rehabilitation' | 'Urgent Care' | 'Skilled Nursing' | 'Home Health'
  city: string
  state: string
  departments: string[]
  specialties: string[]
  facilityManager: string
  primaryContact: string
  timezone: string
  notes: string
}

export const CLIENTS: Client[] = [
  { id: 'cl1',  name: 'Houston Methodist',        displayName: 'Houston Methodist',        legalName: 'Houston Methodist Hospital System',   industry: 'Healthcare', companyType: 'direct', status: 'active', website: 'houstonmethodist.org',     taxId: '74-1234567', companySize: '10,000+',    city: 'Houston',    state: 'TX', country: 'USA', zip: '77030', timezone: 'America/Chicago',    accountOwner: 'Arun Kumar',   recruitmentManager: 'Sarah M.',  primaryRecruiter: 'Sarah M.',   clientSince: 'Jan 2023', lastActivity: '2 hours ago',  tags: ['Hot', 'Travel Nursing'],   preferredCommunication: 'Email', preferredSubmissionMethod: 'VMS Portal', preferredResumeFormat: 'PDF', preferredInterviewProcess: '2 rounds — phone screen then panel', specialInstructions: 'Requires BLS/ACLS on file before submission.' },
  { id: 'cl2',  name: 'Memorial Hermann',         displayName: 'Memorial Hermann',         legalName: 'Memorial Hermann Health System',      industry: 'Healthcare', companyType: 'direct', status: 'active', website: 'memorialhermann.org',      taxId: '74-2234567', companySize: '10,000+',    city: 'Houston',    state: 'TX', country: 'USA', zip: '77070', timezone: 'America/Chicago',    accountOwner: 'Arun Kumar',   recruitmentManager: 'Emily T.',  primaryRecruiter: 'Emily T.',   clientSince: 'Mar 2023', lastActivity: '1 day ago',    tags: ['Hot'],                     preferredCommunication: 'Phone', preferredSubmissionMethod: 'Email',      preferredResumeFormat: 'PDF', preferredInterviewProcess: '1 round — unit manager', specialInstructions: 'Prefers candidates local to Houston metro.' },
  { id: 'cl3',  name: 'Metro Health',             displayName: 'Metro Health',             legalName: 'Metro Health Systems Inc.',           industry: 'Healthcare', companyType: 'direct', status: 'active', website: 'metrohealth.com',          taxId: '75-3234567', companySize: '1,000-5,000', city: 'Dallas',     state: 'TX', country: 'USA', zip: '75201', timezone: 'America/Chicago',    accountOwner: 'James R.',     recruitmentManager: 'James R.',  primaryRecruiter: 'James R.',   clientSince: 'Jun 2023', lastActivity: '3 days ago',   tags: [],                          preferredCommunication: 'Email', preferredSubmissionMethod: 'Email',      preferredResumeFormat: 'Word', preferredInterviewProcess: '2 rounds', specialInstructions: '' },
  { id: 'cl4',  name: "St. Luke's Hospital",      displayName: "St. Luke's Hospital",      legalName: "St. Luke's Health System",            industry: 'Healthcare', companyType: 'direct', status: 'active', website: 'stlukeshealth.org',        taxId: '74-4234567', companySize: '5,000-10,000', city: 'Houston',   state: 'TX', country: 'USA', zip: '77002', timezone: 'America/Chicago',    accountOwner: 'Arun Kumar',   recruitmentManager: 'Sarah M.',  primaryRecruiter: 'Sarah M.',   clientSince: 'Feb 2023', lastActivity: '5 hours ago',  tags: ['Travel Nursing'],          preferredCommunication: 'Email', preferredSubmissionMethod: 'VMS Portal', preferredResumeFormat: 'PDF', preferredInterviewProcess: '2 rounds — HR then unit', specialInstructions: 'Weekend interviews not available.' },
  { id: 'cl5',  name: "Texas Children's Hospital",displayName: "Texas Children's Hospital",legalName: "Texas Children's Hospital",           industry: 'Healthcare', companyType: 'direct', status: 'active', website: 'texaschildrens.org',       taxId: '74-5234567', companySize: '10,000+',    city: 'Houston',    state: 'TX', country: 'USA', zip: '77030', timezone: 'America/Chicago',    accountOwner: 'Arun Kumar',   recruitmentManager: 'Emily T.',  primaryRecruiter: 'Emily T.',   clientSince: 'Apr 2023', lastActivity: '1 day ago',    tags: ['Hot', 'NICU'],             preferredCommunication: 'Email', preferredSubmissionMethod: 'Email',      preferredResumeFormat: 'PDF', preferredInterviewProcess: '2 rounds — panel then offer', specialInstructions: 'Pediatric ACLS required for NICU roles.' },
  { id: 'cl6',  name: 'Baylor Scott & White',     displayName: 'Baylor Scott & White',     legalName: 'Baylor Scott & White Health',         industry: 'Healthcare', companyType: 'direct', status: 'active', website: 'bswhealth.com',            taxId: '75-6234567', companySize: '10,000+',    city: 'Dallas',     state: 'TX', country: 'USA', zip: '75246', timezone: 'America/Chicago',    accountOwner: 'James R.',     recruitmentManager: 'James R.',  primaryRecruiter: 'James R.',   clientSince: 'Jul 2023', lastActivity: '2 days ago',   tags: [],                          preferredCommunication: 'Email', preferredSubmissionMethod: 'VMS Portal', preferredResumeFormat: 'PDF', preferredInterviewProcess: '1 round', specialInstructions: '' },
  { id: 'cl7',  name: 'HCA Houston Healthcare',   displayName: 'HCA Houston Healthcare',   legalName: 'HCA Houston Healthcare LLC',          industry: 'Healthcare', companyType: 'vms',    status: 'active', website: 'hcahoustonhealthcare.com', taxId: '74-7234567', companySize: '10,000+',    city: 'Houston',    state: 'TX', country: 'USA', zip: '77024', timezone: 'America/Chicago',    accountOwner: 'Sarah M.',     recruitmentManager: 'Sarah M.',  primaryRecruiter: 'Sarah M.',   clientSince: 'May 2023', lastActivity: '4 days ago',   tags: ['VMS'],                     preferredCommunication: 'VMS Portal', preferredSubmissionMethod: 'VMS Portal', preferredResumeFormat: 'PDF', preferredInterviewProcess: '2 rounds', specialInstructions: 'All submissions must route through Beeline.' },
  { id: 'cl8',  name: "Children's Medical Center",displayName: "Children's Medical Center",legalName: "Children's Medical Center Dallas",    industry: 'Healthcare', companyType: 'direct', status: 'active', website: 'childrens.com',            taxId: '75-8234567', companySize: '5,000-10,000', city: 'Dallas',    state: 'TX', country: 'USA', zip: '75235', timezone: 'America/Chicago',    accountOwner: 'James R.',     recruitmentManager: 'James R.',  primaryRecruiter: 'James R.',   clientSince: 'Aug 2023', lastActivity: '6 days ago',   tags: ['PICU'],                    preferredCommunication: 'Email', preferredSubmissionMethod: 'Email',      preferredResumeFormat: 'PDF', preferredInterviewProcess: '2 rounds', specialInstructions: '' },
  { id: 'cl9',  name: 'City Hospital',            displayName: 'City Hospital',            legalName: 'City Hospital Corporation',           industry: 'Healthcare', companyType: 'direct', status: 'active', website: 'cityhospital.com',         taxId: '75-9234567', companySize: '1,000-5,000', city: 'Dallas',     state: 'TX', country: 'USA', zip: '75390', timezone: 'America/Chicago',    accountOwner: 'Emily T.',     recruitmentManager: 'Emily T.',  primaryRecruiter: 'Emily T.',   clientSince: 'Sep 2023', lastActivity: '1 week ago',   tags: [],                          preferredCommunication: 'Phone', preferredSubmissionMethod: 'Email',      preferredResumeFormat: 'Word', preferredInterviewProcess: '1 round', specialInstructions: '' },
  { id: 'cl10', name: 'RehabCare',                displayName: 'RehabCare',                legalName: 'RehabCare Group Inc.',                industry: 'Healthcare', companyType: 'direct', status: 'active', website: 'rehabcare.com',            taxId: '43-1034567', companySize: '1,000-5,000', city: 'Fort Worth', state: 'TX', country: 'USA', zip: '76102', timezone: 'America/Chicago',    accountOwner: 'Emily T.',     recruitmentManager: 'Emily T.',  primaryRecruiter: 'Emily T.',   clientSince: 'Oct 2023', lastActivity: '2 weeks ago',  tags: [],                          preferredCommunication: 'Email', preferredSubmissionMethod: 'Email',      preferredResumeFormat: 'PDF', preferredInterviewProcess: '1 round', specialInstructions: '' },
  { id: 'cl11', name: 'City General Hospital',    displayName: 'City General Hospital',    legalName: 'City General Hospital Inc.',          industry: 'Healthcare', companyType: 'direct', status: 'active', website: 'citygeneral.com',          taxId: '75-1134567', companySize: '1,000-5,000', city: 'Austin',     state: 'TX', country: 'USA', zip: '78701', timezone: 'America/Chicago',    accountOwner: 'Sarah M.',     recruitmentManager: 'Sarah M.',  primaryRecruiter: 'Sarah M.',   clientSince: 'Nov 2023', lastActivity: '3 weeks ago',  tags: [],                          preferredCommunication: 'Email', preferredSubmissionMethod: 'Email',      preferredResumeFormat: 'PDF', preferredInterviewProcess: '1 round', specialInstructions: '' },
  { id: 'cl12', name: 'Memorial Health',          displayName: 'Memorial Health',          legalName: 'Memorial Health System',              industry: 'Healthcare', companyType: 'direct', status: 'active', website: 'memorialhealth.com',       taxId: '75-1234568', companySize: '1,000-5,000', city: 'San Antonio',state: 'TX', country: 'USA', zip: '78205', timezone: 'America/Chicago',    accountOwner: 'James R.',     recruitmentManager: 'James R.',  primaryRecruiter: 'James R.',   clientSince: 'Dec 2023', lastActivity: '1 month ago',  tags: [],                          preferredCommunication: 'Email', preferredSubmissionMethod: 'Email',      preferredResumeFormat: 'PDF', preferredInterviewProcess: '1 round', specialInstructions: '' },
  { id: 'cl13', name: 'Memorial Medical',         displayName: 'Memorial Medical',         legalName: 'Memorial Medical Center',             industry: 'Healthcare', companyType: 'direct', status: 'active', website: 'memorialmedical.com',      taxId: '75-1334567', companySize: '1,000-5,000', city: 'Houston',    state: 'TX', country: 'USA', zip: '77025', timezone: 'America/Chicago',    accountOwner: 'Emily T.',     recruitmentManager: 'Emily T.',  primaryRecruiter: 'Emily T.',   clientSince: 'Jan 2024', lastActivity: '5 days ago',   tags: [],                          preferredCommunication: 'Email', preferredSubmissionMethod: 'Email',      preferredResumeFormat: 'PDF', preferredInterviewProcess: '1 round', specialInstructions: '' },
  { id: 'cl14', name: 'AMN Healthcare',           displayName: 'AMN Healthcare',           legalName: 'AMN Healthcare Services Inc.',        industry: 'Healthcare', companyType: 'vms',    status: 'active', website: 'amnhealthcare.com',        taxId: '06-1500000', companySize: '10,000+',    city: 'San Diego',  state: 'CA', country: 'USA', zip: '92130', timezone: 'America/Los_Angeles',accountOwner: 'Sarah M.',     recruitmentManager: 'Sarah M.',  primaryRecruiter: 'Sarah M.',   clientSince: 'Feb 2024', lastActivity: '1 week ago',   tags: ['VMS'],                     preferredCommunication: 'VMS Portal', preferredSubmissionMethod: 'VMS Portal', preferredResumeFormat: 'PDF', preferredInterviewProcess: '2 rounds', specialInstructions: 'Vendor management system — submit via portal only.' },
  { id: 'cl15', name: 'Cross Country',            displayName: 'Cross Country',            legalName: 'Cross Country Healthcare Inc.',       industry: 'Healthcare', companyType: 'vms',    status: 'active', website: 'crosscountry.com',         taxId: '13-3336000', companySize: '5,000-10,000', city: 'Boca Raton',state: 'FL', country: 'USA', zip: '33431', timezone: 'America/New_York',   accountOwner: 'Emily T.',     recruitmentManager: 'Emily T.',  primaryRecruiter: 'Emily T.',   clientSince: 'Mar 2024', lastActivity: '2 weeks ago',  tags: ['VMS'],                     preferredCommunication: 'VMS Portal', preferredSubmissionMethod: 'VMS Portal', preferredResumeFormat: 'PDF', preferredInterviewProcess: '2 rounds', specialInstructions: '' },
  { id: 'cl16', name: 'Sunrise Care',             displayName: 'Sunrise Care',             legalName: 'Sunrise Care Corporation',            industry: 'Healthcare', companyType: 'direct', status: 'active', website: 'sunrisecare.com',          taxId: '75-1434567', companySize: '500-1,000',  city: 'Plano',      state: 'TX', country: 'USA', zip: '75024', timezone: 'America/Chicago',    accountOwner: 'James R.',     recruitmentManager: 'James R.',  primaryRecruiter: 'James R.',   clientSince: 'Apr 2024', lastActivity: '3 weeks ago',  tags: [],                          preferredCommunication: 'Email', preferredSubmissionMethod: 'Email',      preferredResumeFormat: 'Word', preferredInterviewProcess: '1 round', specialInstructions: '' },
  { id: 'cl17', name: 'Regional Hospital',        displayName: 'Regional Hospital',        legalName: 'Regional Hospital Group',             industry: 'Healthcare', companyType: 'direct', status: 'active', website: 'regionalhospital.com',     taxId: '75-1534567', companySize: '1,000-5,000', city: 'Fort Worth', state: 'TX', country: 'USA', zip: '76104', timezone: 'America/Chicago',    accountOwner: 'Sarah M.',     recruitmentManager: 'Sarah M.',  primaryRecruiter: 'Sarah M.',   clientSince: 'May 2024', lastActivity: '1 month ago',  tags: [],                          preferredCommunication: 'Email', preferredSubmissionMethod: 'Email',      preferredResumeFormat: 'PDF', preferredInterviewProcess: '1 round', specialInstructions: '' },
  { id: 'cl18', name: 'UT Southwestern',          displayName: 'UT Southwestern',          legalName: 'UT Southwestern Medical Center',      industry: 'Healthcare', companyType: 'direct', status: 'active', website: 'utsouthwestern.edu',       taxId: '75-1634567', companySize: '10,000+',    city: 'Dallas',     state: 'TX', country: 'USA', zip: '75390', timezone: 'America/Chicago',    accountOwner: 'James R.',     recruitmentManager: 'James R.',  primaryRecruiter: 'James R.',   clientSince: 'Jun 2024', lastActivity: '2 months ago', tags: [],                          preferredCommunication: 'Email', preferredSubmissionMethod: 'Email',      preferredResumeFormat: 'PDF', preferredInterviewProcess: '2 rounds', specialInstructions: '' },
  { id: 'cl19', name: 'Lab Partners',             displayName: 'Lab Partners',             legalName: 'Lab Partners LLC',                    industry: 'Healthcare', companyType: 'direct', status: 'active', website: 'labpartners.com',          taxId: '75-1734567', companySize: '100-500',    city: 'Austin',     state: 'TX', country: 'USA', zip: '78744', timezone: 'America/Chicago',    accountOwner: 'Sarah M.',     recruitmentManager: 'Sarah M.',  primaryRecruiter: 'Sarah M.',   clientSince: 'Jul 2024', lastActivity: '2 months ago', tags: [],                          preferredCommunication: 'Email', preferredSubmissionMethod: 'Email',      preferredResumeFormat: 'PDF', preferredInterviewProcess: '1 round', specialInstructions: '' },

  { id: 'cl20', name: 'Dell Technologies',        displayName: 'Dell Technologies',        legalName: 'Dell Technologies Inc.',              industry: 'IT', companyType: 'direct', status: 'active', website: 'dell.com',                 taxId: '74-2934500', companySize: '10,000+',    city: 'Austin',     state: 'TX', country: 'USA', zip: '78682', timezone: 'America/Chicago',    accountOwner: 'Arun Kumar',   recruitmentManager: 'Priya S.',  primaryRecruiter: 'Priya S.',   clientSince: 'Jan 2023', lastActivity: '3 hours ago',  tags: ['Hot'],                     preferredCommunication: 'Email', preferredSubmissionMethod: 'ATS Integration', preferredResumeFormat: 'PDF', preferredInterviewProcess: '3 rounds — phone, technical, panel', specialInstructions: 'Technical screen required before client submission.' },
  { id: 'cl21', name: 'TechCorp Inc',             displayName: 'TechCorp Inc',             legalName: 'TechCorp Incorporated',               industry: 'IT', companyType: 'direct', status: 'active', website: 'techcorp.com',             taxId: '13-4034500', companySize: '1,000-5,000', city: 'Austin',    state: 'TX', country: 'USA', zip: '78701', timezone: 'America/Chicago',    accountOwner: 'Arun Kumar',   recruitmentManager: 'Arun Kumar',primaryRecruiter: 'Arun Kumar', clientSince: 'Feb 2023', lastActivity: '1 hour ago',   tags: ['Hot'],                     preferredCommunication: 'Email', preferredSubmissionMethod: 'Email',           preferredResumeFormat: 'PDF', preferredInterviewProcess: '2 rounds — technical then final', specialInstructions: '' },
  { id: 'cl22', name: 'CloudBase',                displayName: 'CloudBase',                legalName: 'CloudBase Systems Inc.',              industry: 'IT', companyType: 'direct', status: 'active', website: 'cloudbase.io',             taxId: '46-4134500', companySize: '500-1,000',  city: 'Denver',     state: 'CO', country: 'USA', zip: '80202', timezone: 'America/Denver',     accountOwner: 'Arun Kumar',   recruitmentManager: 'Arun Kumar',primaryRecruiter: 'Arun Kumar', clientSince: 'Mar 2023', lastActivity: '4 hours ago',  tags: [],                          preferredCommunication: 'Email', preferredSubmissionMethod: 'Email',           preferredResumeFormat: 'PDF', preferredInterviewProcess: '2 rounds', specialInstructions: '' },
  { id: 'cl23', name: 'Accenture',                displayName: 'Accenture',                legalName: 'Accenture LLP',                       industry: 'Professional Services', companyType: 'vms', status: 'active', website: 'accenture.com',   taxId: '13-1234560', companySize: '10,000+',    city: 'Chicago',    state: 'IL', country: 'USA', zip: '60601', timezone: 'America/Chicago',    accountOwner: 'Sarah M.',     recruitmentManager: 'Sarah M.',  primaryRecruiter: 'Sarah M.',   clientSince: 'Apr 2023', lastActivity: '2 days ago',   tags: ['VMS'],                     preferredCommunication: 'VMS Portal', preferredSubmissionMethod: 'VMS Portal', preferredResumeFormat: 'Word', preferredInterviewProcess: '2 rounds', specialInstructions: '' },
  { id: 'cl24', name: 'IBM',                      displayName: 'IBM',                      legalName: 'International Business Machines Corp.',industry: 'IT', companyType: 'direct', status: 'active', website: 'ibm.com',                 taxId: '13-0871985', companySize: '10,000+',    city: 'Armonk',     state: 'NY', country: 'USA', zip: '10504', timezone: 'America/New_York',   accountOwner: 'James R.',     recruitmentManager: 'James R.',  primaryRecruiter: 'James R.',   clientSince: 'May 2023', lastActivity: '3 days ago',   tags: [],                          preferredCommunication: 'Email', preferredSubmissionMethod: 'Email',           preferredResumeFormat: 'PDF', preferredInterviewProcess: '2 rounds', specialInstructions: '' },
  { id: 'cl25', name: 'Cisco',                    displayName: 'Cisco',                    legalName: 'Cisco Systems Inc.',                  industry: 'IT', companyType: 'direct', status: 'active', website: 'cisco.com',                taxId: '77-0059951', companySize: '10,000+',    city: 'San Jose',   state: 'CA', country: 'USA', zip: '95134', timezone: 'America/Los_Angeles',accountOwner: 'James R.',     recruitmentManager: 'James R.',  primaryRecruiter: 'James R.',   clientSince: 'Jun 2023', lastActivity: '1 week ago',   tags: [],                          preferredCommunication: 'Email', preferredSubmissionMethod: 'Email',           preferredResumeFormat: 'PDF', preferredInterviewProcess: '2 rounds', specialInstructions: '' },
  { id: 'cl26', name: 'Cognizant',                displayName: 'Cognizant',                legalName: 'Cognizant Technology Solutions',      industry: 'Professional Services', companyType: 'vms', status: 'active', website: 'cognizant.com',   taxId: '13-3728359', companySize: '10,000+',    city: 'Teaneck',    state: 'NJ', country: 'USA', zip: '07666', timezone: 'America/New_York',   accountOwner: 'Emily T.',     recruitmentManager: 'Emily T.',  primaryRecruiter: 'Emily T.',   clientSince: 'Jul 2023', lastActivity: '2 weeks ago',  tags: ['VMS'],                     preferredCommunication: 'VMS Portal', preferredSubmissionMethod: 'VMS Portal', preferredResumeFormat: 'Word', preferredInterviewProcess: '1 round', specialInstructions: '' },
  { id: 'cl27', name: 'NetSec Corp',              displayName: 'NetSec Corp',              legalName: 'NetSec Corporation',                  industry: 'IT', companyType: 'direct', status: 'active', website: 'netseccorp.com',           taxId: '46-1834500', companySize: '100-500',   city: 'Plano',      state: 'TX', country: 'USA', zip: '75024', timezone: 'America/Chicago',    accountOwner: 'James R.',     recruitmentManager: 'James R.',  primaryRecruiter: 'James R.',   clientSince: 'Aug 2023', lastActivity: '3 days ago',   tags: [],                          preferredCommunication: 'Email', preferredSubmissionMethod: 'Email',           preferredResumeFormat: 'PDF', preferredInterviewProcess: '2 rounds', specialInstructions: '' },
  { id: 'cl28', name: 'AI Startup',               displayName: 'AI Startup',               legalName: 'AI Startup Technologies Inc.',        industry: 'IT', companyType: 'direct', status: 'active', website: 'aistartup.io',             taxId: '46-1934500', companySize: '1-100',     city: 'San Francisco',state: 'CA', country: 'USA', zip: '94105', timezone: 'America/Los_Angeles',accountOwner: 'Emily T.',     recruitmentManager: 'Emily T.',  primaryRecruiter: 'Emily T.',   clientSince: 'Sep 2023', lastActivity: '5 days ago',   tags: [],                          preferredCommunication: 'Email', preferredSubmissionMethod: 'Email',           preferredResumeFormat: 'PDF', preferredInterviewProcess: '3 rounds', specialInstructions: '' },
  { id: 'cl29', name: 'Analytics Co',             displayName: 'Analytics Co',             legalName: 'Analytics Co LLC',                    industry: 'IT', companyType: 'direct', status: 'active', website: 'analyticsco.com',          taxId: '46-2034500', companySize: '100-500',   city: 'Chicago',    state: 'IL', country: 'USA', zip: '60602', timezone: 'America/Chicago',    accountOwner: 'James R.',     recruitmentManager: 'James R.',  primaryRecruiter: 'James R.',   clientSince: 'Oct 2023', lastActivity: '1 week ago',   tags: [],                          preferredCommunication: 'Email', preferredSubmissionMethod: 'Email',           preferredResumeFormat: 'PDF', preferredInterviewProcess: '2 rounds', specialInstructions: '' },
  { id: 'cl30', name: 'DataStream',               displayName: 'DataStream',               legalName: 'DataStream Analytics Inc.',           industry: 'IT', companyType: 'direct', status: 'active', website: 'datastream.io',            taxId: '46-2134500', companySize: '500-1,000', city: 'Chicago',    state: 'IL', country: 'USA', zip: '60603', timezone: 'America/Chicago',    accountOwner: 'Sarah M.',     recruitmentManager: 'Sarah M.',  primaryRecruiter: 'Sarah M.',   clientSince: 'Nov 2023', lastActivity: '2 weeks ago',  tags: [],                          preferredCommunication: 'Email', preferredSubmissionMethod: 'Email',           preferredResumeFormat: 'PDF', preferredInterviewProcess: '2 rounds', specialInstructions: '' },
  { id: 'cl31', name: 'FinCore Inc',              displayName: 'FinCore Inc',              legalName: 'FinCore Incorporated',                industry: 'Finance', companyType: 'direct', status: 'active', website: 'fincore.com',              taxId: '46-2234500', companySize: '1,000-5,000', city: 'Austin',    state: 'TX', country: 'USA', zip: '78701', timezone: 'America/Chicago',    accountOwner: 'Arun Kumar',   recruitmentManager: 'Arun Kumar',primaryRecruiter: 'Arun Kumar', clientSince: 'Dec 2023', lastActivity: '4 days ago',   tags: [],                          preferredCommunication: 'Email', preferredSubmissionMethod: 'Email',           preferredResumeFormat: 'PDF', preferredInterviewProcess: '2 rounds', specialInstructions: '' },
  { id: 'cl32', name: 'Creative Labs',            displayName: 'Creative Labs',            legalName: 'Creative Labs Design Inc.',           industry: 'Professional Services', companyType: 'direct', status: 'active', website: 'creativelabs.com', taxId: '46-2334500', companySize: '100-500',   city: 'Denver',     state: 'CO', country: 'USA', zip: '80203', timezone: 'America/Denver',      accountOwner: 'Emily T.',     recruitmentManager: 'Emily T.',  primaryRecruiter: 'Emily T.',   clientSince: 'Jan 2024', lastActivity: '1 week ago',   tags: [],                          preferredCommunication: 'Email', preferredSubmissionMethod: 'Email',           preferredResumeFormat: 'PDF', preferredInterviewProcess: '2 rounds — portfolio review', specialInstructions: '' },

  { id: 'cl33', name: 'JPMorgan Chase',           displayName: 'JPMorgan Chase',           legalName: 'JPMorgan Chase & Co.',                industry: 'Finance', companyType: 'vms', status: 'active', website: 'jpmorganchase.com',        taxId: '13-2624428', companySize: '10,000+',    city: 'New York',   state: 'NY', country: 'USA', zip: '10017', timezone: 'America/New_York',   accountOwner: 'Arun Kumar',   recruitmentManager: 'Arun Kumar',primaryRecruiter: 'Arun Kumar', clientSince: 'Jan 2023', lastActivity: '2 hours ago',  tags: ['Hot', 'VMS'],              preferredCommunication: 'VMS Portal', preferredSubmissionMethod: 'VMS Portal', preferredResumeFormat: 'PDF', preferredInterviewProcess: '3 rounds — screen, technical, panel', specialInstructions: 'All candidates require background + credit check.' },
  { id: 'cl34', name: 'Bank of America',          displayName: 'Bank of America',          legalName: 'Bank of America Corporation',         industry: 'Finance', companyType: 'vms', status: 'active', website: 'bankofamerica.com',        taxId: '56-0906609', companySize: '10,000+',    city: 'Charlotte',  state: 'NC', country: 'USA', zip: '28255', timezone: 'America/New_York',   accountOwner: 'James R.',     recruitmentManager: 'James R.',  primaryRecruiter: 'James R.',   clientSince: 'Feb 2023', lastActivity: '1 week ago',   tags: ['VMS'],                     preferredCommunication: 'VMS Portal', preferredSubmissionMethod: 'VMS Portal', preferredResumeFormat: 'PDF', preferredInterviewProcess: '2 rounds', specialInstructions: '' },
  { id: 'cl35', name: 'FinTech Ltd',              displayName: 'FinTech Ltd',              legalName: 'FinTech Ltd.',                        industry: 'Finance', companyType: 'direct', status: 'active', website: 'fintechltd.com',           taxId: '46-2434500', companySize: '500-1,000', city: 'New York',   state: 'NY', country: 'USA', zip: '10005', timezone: 'America/New_York',   accountOwner: 'Sarah M.',     recruitmentManager: 'Sarah M.',  primaryRecruiter: 'Sarah M.',   clientSince: 'Mar 2023', lastActivity: '3 days ago',   tags: [],                          preferredCommunication: 'Email', preferredSubmissionMethod: 'Email',           preferredResumeFormat: 'PDF', preferredInterviewProcess: '2 rounds', specialInstructions: '' },
  { id: 'cl36', name: 'FinServ LLC',              displayName: 'FinServ LLC',              legalName: 'FinServ LLC',                         industry: 'Finance', companyType: 'direct', status: 'active', website: 'finservllc.com',           taxId: '46-2534500', companySize: '100-500',   city: 'Chicago',    state: 'IL', country: 'USA', zip: '60604', timezone: 'America/Chicago',     accountOwner: 'James R.',     recruitmentManager: 'James R.',  primaryRecruiter: 'James R.',   clientSince: 'Apr 2023', lastActivity: '2 weeks ago',  tags: [],                          preferredCommunication: 'Email', preferredSubmissionMethod: 'Email',           preferredResumeFormat: 'PDF', preferredInterviewProcess: '1 round', specialInstructions: '' },

  { id: 'cl37', name: 'Shell',                    displayName: 'Shell',                    legalName: 'Shell USA Inc.',                      industry: 'Other', companyType: 'direct', status: 'active', website: 'shell.us',                 taxId: '74-2634500', companySize: '10,000+',    city: 'Houston',    state: 'TX', country: 'USA', zip: '77002', timezone: 'America/Chicago',    accountOwner: 'Arun Kumar',   recruitmentManager: 'Arun Kumar',primaryRecruiter: 'Arun Kumar', clientSince: 'Jan 2023', lastActivity: '5 hours ago',  tags: ['Hot'],                     preferredCommunication: 'Email', preferredSubmissionMethod: 'Email',           preferredResumeFormat: 'PDF', preferredInterviewProcess: '3 rounds', specialInstructions: '' },
  { id: 'cl38', name: 'Chevron',                  displayName: 'Chevron',                  legalName: 'Chevron Corporation',                 industry: 'Other', companyType: 'direct', status: 'active', website: 'chevron.com',              taxId: '94-0890210', companySize: '10,000+',    city: 'Houston',    state: 'TX', country: 'USA', zip: '77002', timezone: 'America/Chicago',    accountOwner: 'Arun Kumar',   recruitmentManager: 'Arun Kumar',primaryRecruiter: 'Arun Kumar', clientSince: 'Feb 2023', lastActivity: '1 day ago',    tags: [],                          preferredCommunication: 'Email', preferredSubmissionMethod: 'Email',           preferredResumeFormat: 'PDF', preferredInterviewProcess: '2 rounds', specialInstructions: '' },
  { id: 'cl39', name: 'ExxonMobil',               displayName: 'ExxonMobil',               legalName: 'Exxon Mobil Corporation',             industry: 'Other', companyType: 'direct', status: 'active', website: 'exxonmobil.com',           taxId: '13-5409005', companySize: '10,000+',    city: 'Irving',     state: 'TX', country: 'USA', zip: '75039', timezone: 'America/Chicago',    accountOwner: 'James R.',     recruitmentManager: 'James R.',  primaryRecruiter: 'James R.',   clientSince: 'Mar 2023', lastActivity: '1 week ago',   tags: [],                          preferredCommunication: 'Email', preferredSubmissionMethod: 'Email',           preferredResumeFormat: 'PDF', preferredInterviewProcess: '2 rounds', specialInstructions: '' },
  { id: 'cl40', name: 'AT&T',                     displayName: 'AT&T',                     legalName: 'AT&T Inc.',                           industry: 'IT', companyType: 'vms', status: 'active', website: 'att.com',                  taxId: '43-1301883', companySize: '10,000+',    city: 'Dallas',     state: 'TX', country: 'USA', zip: '75202', timezone: 'America/Chicago',    accountOwner: 'Arun Kumar',   recruitmentManager: 'Arun Kumar',primaryRecruiter: 'Arun Kumar', clientSince: 'Jan 2023', lastActivity: '3 hours ago',  tags: ['VMS'],                     preferredCommunication: 'VMS Portal', preferredSubmissionMethod: 'VMS Portal', preferredResumeFormat: 'PDF', preferredInterviewProcess: '2 rounds', specialInstructions: '' },
  { id: 'cl41', name: 'BuildRight',               displayName: 'BuildRight',               legalName: 'BuildRight Construction Co.',         industry: 'Engineering', companyType: 'direct', status: 'active', website: 'buildright.com',         taxId: '46-2734500', companySize: '500-1,000', city: 'Denver',     state: 'CO', country: 'USA', zip: '80204', timezone: 'America/Denver',      accountOwner: 'Emily T.',     recruitmentManager: 'Emily T.',  primaryRecruiter: 'Emily T.',   clientSince: 'May 2023', lastActivity: '4 days ago',   tags: [],                          preferredCommunication: 'Email', preferredSubmissionMethod: 'Email',           preferredResumeFormat: 'PDF', preferredInterviewProcess: '2 rounds', specialInstructions: '' },
  { id: 'cl42', name: 'Amazon Logistics',         displayName: 'Amazon Logistics',         legalName: 'Amazon Logistics Inc.',               industry: 'Other', companyType: 'vms', status: 'active', website: 'amazon.com',               taxId: '91-1646860', companySize: '10,000+',    city: 'Seattle',    state: 'WA', country: 'USA', zip: '98109', timezone: 'America/Los_Angeles',accountOwner: 'Sarah M.',     recruitmentManager: 'Sarah M.',  primaryRecruiter: 'Sarah M.',   clientSince: 'Jun 2023', lastActivity: '2 days ago',   tags: ['VMS'],                     preferredCommunication: 'VMS Portal', preferredSubmissionMethod: 'VMS Portal', preferredResumeFormat: 'PDF', preferredInterviewProcess: '1 round', specialInstructions: '' },
  { id: 'cl43', name: 'RetailCo',                 displayName: 'RetailCo',                 legalName: 'RetailCo Enterprises Inc.',           industry: 'Other', companyType: 'direct', status: 'active', website: 'retailco.com',             taxId: '46-2834500', companySize: '1,000-5,000', city: 'Chicago',   state: 'IL', country: 'USA', zip: '60605', timezone: 'America/Chicago',    accountOwner: 'James R.',     recruitmentManager: 'James R.',  primaryRecruiter: 'James R.',   clientSince: 'Jul 2023', lastActivity: '1 week ago',   tags: [],                          preferredCommunication: 'Email', preferredSubmissionMethod: 'Email',           preferredResumeFormat: 'PDF', preferredInterviewProcess: '2 rounds', specialInstructions: '' },
]

export const CLIENT_CONTACTS: ClientContact[] = [
  { id: 'cc1', clientId: 'cl1',  name: 'Dr. Sarah Kim',      title: 'Director of Nursing',      department: 'ICU',       email: 'sarah.kim@houstonmethodist.org',  phone: '(713) 555-0101', mobile: '(713) 555-0102', linkedin: 'linkedin.com/in/sarahkim',     preferredContactMethod: 'Email', decisionMaker: true,  primary: true,  status: 'active', notes: 'Prefers morning calls before 10am.' },
  { id: 'cc2', clientId: 'cl1',  name: 'Mark Reynolds',      title: 'VMS Coordinator',          department: 'HR',        email: 'mark.reynolds@houstonmethodist.org', phone: '(713) 555-0103', mobile: '',              linkedin: '',                              preferredContactMethod: 'Email', decisionMaker: false, primary: false, status: 'active', notes: '' },
  { id: 'cc3', clientId: 'cl2',  name: 'Dr. Kevin Walsh',    title: 'Chief Nursing Officer',    department: 'Nursing',   email: 'kevin.walsh@memorialhermann.org', phone: '(713) 555-0201', mobile: '(713) 555-0202', linkedin: 'linkedin.com/in/kevinwalsh',   preferredContactMethod: 'Phone', decisionMaker: true,  primary: true,  status: 'active', notes: '' },
  { id: 'cc4', clientId: 'cl5',  name: 'Dr. Priya Nair',     title: 'NICU Manager',             department: 'NICU',      email: 'priya.nair@texaschildrens.org',   phone: '(713) 555-0501', mobile: '(713) 555-0502', linkedin: '',                              preferredContactMethod: 'Email', decisionMaker: true,  primary: true,  status: 'active', notes: 'Requires pediatric ACLS confirmation before interview.' },
  { id: 'cc5', clientId: 'cl20', name: "James O'Brien",     title: 'Engineering Manager',      department: 'Cloud Infrastructure', email: 'jobrien@dell.com', phone: '(512) 555-2001', mobile: '(512) 555-2002', linkedin: 'linkedin.com/in/jobrien', preferredContactMethod: 'Email', decisionMaker: true,  primary: true,  status: 'active', notes: '' },
  { id: 'cc6', clientId: 'cl21', name: 'Rachel Brown',       title: 'Talent Acquisition Lead',  department: 'HR',        email: 'rachel.brown@techcorp.com',      phone: '(512) 555-2101', mobile: '',              linkedin: 'linkedin.com/in/rachelbrown', preferredContactMethod: 'Email', decisionMaker: true,  primary: true,  status: 'active', notes: '' },
  { id: 'cc7', clientId: 'cl33', name: 'Mike Torres',        title: 'VP of Technology',         department: 'Technology', email: 'mike.torres@jpmorganchase.com', phone: '(212) 555-3301', mobile: '(212) 555-3302', linkedin: 'linkedin.com/in/miketorres', preferredContactMethod: 'VMS Portal', decisionMaker: true, primary: true, status: 'active', notes: 'All communication must reference the requisition number.' },
  { id: 'cc8', clientId: 'cl37', name: 'Linda Park',         title: 'Recruiting Manager',       department: 'Talent',    email: 'linda.park@shell.us',            phone: '(713) 555-3701', mobile: '', linkedin: '',                                       preferredContactMethod: 'Email', decisionMaker: true, primary: true, status: 'active', notes: '' },
]

export const CLIENT_FACILITIES: ClientFacility[] = [
  { id: 'cf1', clientId: 'cl1', name: 'Houston Methodist Hospital — Texas Medical Center', type: 'Hospital', city: 'Houston', state: 'TX', departments: ['ICU', 'ER', 'Surgical'],      specialties: ['Critical Care', 'Cardiology'],   facilityManager: 'Dr. Sarah Kim',   primaryContact: 'Dr. Sarah Kim',   timezone: 'America/Chicago', notes: 'Flagship facility, highest volume.' },
  { id: 'cf2', clientId: 'cl1', name: 'Houston Methodist West Hospital',                    type: 'Hospital', city: 'Houston', state: 'TX', departments: ['OR', 'L&D'],                  specialties: ['Orthopedics', "Women's Health"], facilityManager: 'Mark Reynolds',   primaryContact: 'Mark Reynolds',   timezone: 'America/Chicago', notes: '' },
  { id: 'cf3', clientId: 'cl2', name: 'Memorial Hermann — Texas Medical Center',            type: 'Hospital', city: 'Houston', state: 'TX', departments: ['ER', 'Telemetry'],           specialties: ['Trauma', 'Cardiology'],          facilityManager: 'Dr. Kevin Walsh', primaryContact: 'Dr. Kevin Walsh', timezone: 'America/Chicago', notes: '' },
  { id: 'cf4', clientId: 'cl5', name: "Texas Children's Hospital — Main Campus",            type: 'Hospital', city: 'Houston', state: 'TX', departments: ['NICU', 'PICU'],               specialties: ['Neonatology', 'Pediatric Critical Care'], facilityManager: 'Dr. Priya Nair', primaryContact: 'Dr. Priya Nair', timezone: 'America/Chicago', notes: 'Level IV NICU.' },
  { id: 'cf5', clientId: 'cl4', name: "St. Luke's Hospital — Medical Center Campus",        type: 'Hospital', city: 'Houston', state: 'TX', departments: ['OR', 'Cardiac'],             specialties: ['Cardiac Surgery'],               facilityManager: 'Unassigned',      primaryContact: 'Unassigned',      timezone: 'America/Chicago', notes: '' },
  { id: 'cf6', clientId: 'cl10', name: 'RehabCare — Fort Worth Rehabilitation Center',       type: 'Rehabilitation', city: 'Fort Worth', state: 'TX', departments: ['Physical Therapy'], specialties: ['Sports Medicine'],               facilityManager: 'Unassigned',      primaryContact: 'Unassigned',      timezone: 'America/Chicago', notes: '' },
  { id: 'cf7', clientId: 'cl19', name: 'Lab Partners — Austin Diagnostics Lab',              type: 'Laboratory', city: 'Austin', state: 'TX', departments: ['Phlebotomy'],           specialties: ['Diagnostics'],                   facilityManager: 'Unassigned',      primaryContact: 'Unassigned',      timezone: 'America/Chicago', notes: '' },
]

export function getClientByName(name: string) {
  return CLIENTS.find(c => c.name === name)
}
export function getClientById(id: string) {
  return CLIENTS.find(c => c.id === id)
}
export function getContactsForClient(clientId: string) {
  return CLIENT_CONTACTS.filter(c => c.clientId === clientId)
}
export function getFacilitiesForClient(clientId: string) {
  return CLIENT_FACILITIES.filter(f => f.clientId === clientId)
}
