'use client'

import { useState } from 'react'
import { Label } from '@/components/ui/label'
import { Button } from '@/components/ui/button'

const ROLES = [
  { role: 'Admin', access: ['All Reports', 'Export', 'Schedule', 'Delete'] },
  { role: 'Manager', access: ['All Reports', 'Export', 'Schedule'] },
  { role: 'Recruiter', access: ['Recruiter Reports', 'Candidate Reports', 'Job Reports'] },
  { role: 'Viewer', access: ['Dashboard', 'Executive Reports'] },
]

export default function ReportSettings() {
  const [aiInsights, setAiInsights] = useState(true)
  const [notify, setNotify] = useState(true)

  return (
    <div className="flex flex-col h-full p-6 gap-5 overflow-y-auto">
      <div>
        <h1 className="text-xl font-semibold">Report Settings</h1>
        <p className="text-sm text-muted-foreground">Configure default behaviors for reports and exports</p>
      </div>

      <div className="grid grid-cols-2 gap-4 max-w-3xl">
        {/* Default Date Range */}
        <div className="rounded-lg border bg-card p-4 flex flex-col gap-3">
          <div>
            <p className="text-sm font-medium">Default Date Range</p>
            <p className="text-sm text-muted-foreground mt-0.5">Used as the default filter across all reports</p>
          </div>
          <select className="h-8 text-sm border rounded-md px-2 bg-background">
            <option>This Month</option>
            <option>Last 7 Days</option>
            <option>Last 30 Days</option>
            <option>Last Quarter</option>
            <option>This Year</option>
          </select>
        </div>

        {/* Default Export Format */}
        <div className="rounded-lg border bg-card p-4 flex flex-col gap-3">
          <div>
            <p className="text-sm font-medium">Default Export Format</p>
            <p className="text-sm text-muted-foreground mt-0.5">Format used when exporting reports</p>
          </div>
          <select className="h-8 text-sm border rounded-md px-2 bg-background">
            <option>Excel</option>
            <option>PDF</option>
            <option>CSV</option>
          </select>
        </div>

        {/* AI Insights Toggle */}
        <div className="rounded-lg border bg-card p-4 flex items-center justify-between">
          <div>
            <p className="text-sm font-medium">AI Insights</p>
            <p className="text-sm text-muted-foreground mt-0.5">Show Claude-powered insights on report pages</p>
          </div>
          <button
            onClick={() => setAiInsights(!aiInsights)}
            className={`relative inline-flex h-5 w-9 items-center rounded-full transition-colors ${aiInsights ? 'bg-emerald-500' : 'bg-muted'}`}
          >
            <span className={`inline-block size-4 rounded-full bg-white shadow transition-transform ${aiInsights ? 'translate-x-4' : 'translate-x-0.5'}`} />
          </button>
        </div>

        {/* Notify Toggle */}
        <div className="rounded-lg border bg-card p-4 flex items-center justify-between">
          <div>
            <p className="text-sm font-medium">Scheduled Report Notifications</p>
            <p className="text-sm text-muted-foreground mt-0.5">Notify when a scheduled report is ready</p>
          </div>
          <button
            onClick={() => setNotify(!notify)}
            className={`relative inline-flex h-5 w-9 items-center rounded-full transition-colors ${notify ? 'bg-emerald-500' : 'bg-muted'}`}
          >
            <span className={`inline-block size-4 rounded-full bg-white shadow transition-transform ${notify ? 'translate-x-4' : 'translate-x-0.5'}`} />
          </button>
        </div>

        {/* Data Refresh */}
        <div className="rounded-lg border bg-card p-4 flex flex-col gap-3">
          <div>
            <p className="text-sm font-medium">Data Refresh Interval</p>
            <p className="text-sm text-muted-foreground mt-0.5">How often report data is refreshed</p>
          </div>
          <select className="h-8 text-sm border rounded-md px-2 bg-background">
            <option>Real-time</option>
            <option>Every 15 min</option>
            <option>Hourly</option>
            <option>Daily</option>
          </select>
        </div>

        {/* Email Signature */}
        <div className="rounded-lg border bg-card p-4 flex flex-col gap-3">
          <div>
            <p className="text-sm font-medium">Email Report Signature</p>
            <p className="text-sm text-muted-foreground mt-0.5">Appended to scheduled report emails</p>
          </div>
          <textarea
            className="min-h-[60px] px-2.5 py-2 text-sm border rounded-md bg-background resize-none focus:outline-none focus:ring-1 focus:ring-ring"
            defaultValue="This report was automatically generated by God Recruiter ATS."
          />
        </div>
      </div>

      {/* Report Permissions */}
      <div className="rounded-lg border bg-card p-4 max-w-3xl">
        <p className="text-sm font-medium mb-3">Report Permissions by Role</p>
        <table className="w-full text-sm">
          <thead>
            <tr className="text-muted-foreground border-b">
              <th className="pb-2 text-left font-medium">Role</th>
              <th className="pb-2 text-left font-medium">Report Access</th>
            </tr>
          </thead>
          <tbody>
            {ROLES.map((r) => (
              <tr key={r.role} className="border-b last:border-0">
                <td className="py-2.5 font-medium">{r.role}</td>
                <td className="py-2.5">
                  <div className="flex flex-wrap gap-1">
                    {r.access.map((a) => (
                      <span key={a} className="px-1.5 py-0.5 rounded text-[10px] bg-muted text-muted-foreground">{a}</span>
                    ))}
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="max-w-3xl">
        <Button size="sm">Save Settings</Button>
      </div>
    </div>
  )
}
